app:
  secret_key: ${SECRET_KEY}
  debug: false
  host: 0.0.0.0
  port: 5000
  workers: 4
  threads: 2
  max_requests: 1000
  max_requests_jitter: 50
  timeout: 30
  keep_alive: 5
  preload_app: true
files:
  upload_folder: /app/uploads
  job_results_folder: /app/job_results
  cache_folder: /app/.cache
  logs_folder: /app/logs
  max_file_size_mb: 16
  allowed_extensions:
  - txt
  - pdf
  - docx
  - doc
logging:
  level: ${LOG_LEVEL:-INFO}
  max_file_size_mb: 10
  backup_count: 5
  format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
  file_handler: true
  console_handler: true
openai:
  model: ${OPENAI_MODEL:-gpt-3.5-turbo}
  temperature: 0.3
  max_retries: 3
  timeout_seconds: 30
  api_key: ${OPENAI_API_KEY}
cache:
  directory: /app/.cache
  expiration_days: 7
  max_size_mb: 100
  cleanup_on_startup: true
  backend: redis
  redis_url: ${REDIS_URL:-redis://redis:6379/0}
job_search:
  default_sites:
  - indeed
  - linkedin
  default_results: 25
  max_results: 200
  hours_old: 72
  default_country: USA
  description_max_length: 500
  default_location: Remote
job_analysis:
  enabled: true
  analyze_salary: true
  rank_by_similarity: true
  max_jobs_to_analyze: 30
  salary_extraction_confidence_threshold: 0.7
  similarity_ranking_model: ${OPENAI_MODEL:-gpt-3.5-turbo}
  batch_size: 5
  cache_analysis_results: true
  parallel_processing: true
  max_parallel_batches: 3
  request_delay_seconds: 1.0
resume_processing:
  pii_removal:
  - enabled
  - preserve_professional_urls
  - professional_domains
cleanup:
  default_days_old: 7
  max_days_old: 365
  auto_cleanup_on_startup: true
ui:
  auto_dismiss_alerts_ms: 5000
  loading_button_timeout_ms: 10000
  max_file_size_display_mb: 16
  job_results_per_page: 30
  animation_duration_ms: 300
development:
  show_debug_info: false
  enable_test_routes: false
  mock_api_calls: false
security:
  enable_csrf_protection: true
  secure_file_uploads: true
  sanitize_filenames: true
  max_upload_attempts: 10
  rate_limit_per_minute: 60
  session_cookie_secure: true
  session_cookie_httponly: true
  session_cookie_samesite: 'Lax'
  permanent_session_lifetime: 1800
health_check:
  enabled: true
  endpoint: /health
  timeout_seconds: 5
